<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8"/>
<!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="#00bfff">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="#00bfff">
<!-- iOS Safari -->
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="template/css/style.css">
<title>Create Session</title>
</head>
<body>
